with source as (
      select * from {{ source('default', 'azure_data_amortized') }}
),
renamed as (
    select
        {{ adapter.quote("BillingPeriodStartDate") }},
        {{ adapter.quote("Date") }},
        {{ adapter.quote("InvoiceSectionName") }},
        {{ adapter.quote("AccountName") }},
        {{ adapter.quote("AccountOwnerId") }},
        {{ adapter.quote("SubscriptionId") }},
        {{ adapter.quote("SubscriptionName") }},
        {{ adapter.quote("ResourceGroup") }},
        {{ adapter.quote("ResourceLocation") }},
        {{ adapter.quote("ProductName") }},
        {{ adapter.quote("MeterCategory") }},
        {{ adapter.quote("MeterSubCategory") }},
        {{ adapter.quote("MeterId") }},
        {{ adapter.quote("MeterName") }},
        {{ adapter.quote("MeterRegion") }},
        {{ adapter.quote("UnitOfMeasure") }},
        {{ adapter.quote("Quantity") }},
        {{ adapter.quote("EffectivePrice") }},
        {{ adapter.quote("CostInBillingCurrency") }},
        {{ adapter.quote("CostCenter") }},
        {{ adapter.quote("ConsumedService") }},
        {{ adapter.quote("ResourceId") }},
        {{ adapter.quote("Tags") }},
        {{ adapter.quote("OfferId") }},
        {{ adapter.quote("AdditionalInfo") }},
        {{ adapter.quote("ServiceInfo1") }},
        {{ adapter.quote("ServiceInfo2") }},
        {{ adapter.quote("ResourceName") }},
        {{ adapter.quote("ReservationId") }},
        {{ adapter.quote("ReservationName") }},
        {{ adapter.quote("UnitPrice") }},
        {{ adapter.quote("ProductOrderId") }},
        {{ adapter.quote("ProductOrderName") }},
        {{ adapter.quote("Term") }},
        {{ adapter.quote("PublisherType") }},
        {{ adapter.quote("PublisherName") }},
        {{ adapter.quote("ChargeType") }},
        {{ adapter.quote("Frequency") }},
        {{ adapter.quote("PricingModel") }},
        {{ adapter.quote("AvailabilityZone") }},
        {{ adapter.quote("BillingAccountId") }},
        {{ adapter.quote("BillingAccountName") }},
        {{ adapter.quote("BillingCurrencyCode") }},
        {{ adapter.quote("BillingPeriodEndDate") }},
        {{ adapter.quote("BillingProfileId") }},
        {{ adapter.quote("BillingProfileName") }},
        {{ adapter.quote("InvoiceSectionId") }},
        {{ adapter.quote("IsAzureCreditEligible") }},
        {{ adapter.quote("PartNumber") }},
        {{ adapter.quote("PayGPrice") }},
        {{ adapter.quote("PlanName") }},
        {{ adapter.quote("ServiceFamily") }},
        {{ adapter.quote("CostAllocationRuleName") }},
        {{ adapter.quote("benefitId") }},
        {{ adapter.quote("benefitName") }}

    from source
)
select * from renamed
  